# Generated by Django 2.1.15 on 2021-05-20 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField()),
                ('evenementiel', models.BooleanField()),
                ('date_evenement', models.DateField()),
                ('auteur', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Community',
            new_name='Communaute',
        ),
        migrations.AddField(
            model_name='post',
            name='communaute',
            field=models.ForeignKey(on_delete='SET_NULL', to='communitymanager.Communaute'),
        ),
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete='CASCADE', to='communitymanager.Priorite'),
        ),
    ]
