# Generated by Django 2.1.15 on 2021-05-20 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0002_auto_20210520_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communaute',
            new_name='Community',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='communaute',
            new_name='community',
        ),
    ]
