# Generated by Django 2.1.15 on 2021-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0003_auto_20210520_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
